auto renew working again

diff --git a/bin/mk b/bin/mk
--- a/bin/mk
+++ b/bin/mk
@@ -15,7 +15,7 @@ else
   trap cleanup EXIT
 fi
 
-if [[ ! -z $AWS_ADMIN_USER ]]; then
+if [[ -z ${AWS_ADMIN_USER} ]]; then
   echo >&2 "ERROR: Must set AWS_ADMIN_USER!"
   exit 1
 fi
@@ -55,15 +55,17 @@ function show_help() {
   mk <COMMAND> <FLAGS>
 
   COMMANDS
-    registry - create/start local registry
-    update - Update this repo and submodule
-    pynode - Build/run the pynode Docker image
-    pulumi - Build/run the pulumi Docker image
-    awsmgr - Build/run the awsmgr (base) Docker imge
-    vice   - Build/run the main vice Docker image
-    clean  - Be careful, this may clear all docker cache.
-    all    - Builds pynode, pulumi, awsmgr then vice in that order.
-    generate-aws-token  -- Generate temporary token for aws
+    registry                - create/start local registry
+    update                  - Update this repo and submodule
+    pynode                  - Build/run the pynode Docker image
+    pulumi                  - Build/run the pulumi Docker image
+    awsmgr                  - Build/run the awsmgr (base) Docker imge
+    vice                    - Build/run the main vice Docker image
+    clean                   - Be careful, this may clear all docker cache.
+    all                     - Builds pynode, pulumi, awsmgr, vice in order.
+    generate-aws-token      - Generate temporary token for aws
+    update-key-from-vice    - If vice is running, clones keys and stashes in
+                              the .env file.
 
     iam-1  - Create IAM Policy for S3
     iam-2  - Create IAM Policy for EC2
@@ -140,63 +142,49 @@ function get_aws_account_id() {
   echo "${aws_account_id}"
 }
 
-# function generate_aws_token() {
-#   if [[ -z ${AWS_ADMIN_PROFILE} ]]; then
-#     AWS_ADMIN_PROFILE=default
-#     echo "AWS_ADMIN_PROFILE='default'" >> ${PRJ_ROOT_DIR}/.env
-#   else
-#     echo "Using AWS Profile: $AWS_ADMIN_PROFILE for your cli profile..."
-#   fi
+update_keys_from_vice() {
+  if ! docker ps --filter "name=vice" | grep vice >/dev/null 2>&1; then
+    >&2 echo "ERROR: vice not running!"
+    return 1
+  fi
 
-#   aws_account_id=$(\
-#       aws sts get-caller-identity --profile $AWS_ADMIN_PROFILE \
-#         | jq -r .Account \
-#       || { \
-#         >&2 echo "ERROR: failed to get AWS Account ID."; \
-#         exit 1; \
-#       } \
-#     )
-#     echo "AWS Account ID: ${aws_account_id}"
-#     # min 900 seconds or 8 hours max?
-#     if [[ ! -z ${aws_account_id} ]]; then
-#       aws_output=$(\
-#         aws --profile ${AWS_ADMIN_PROFILE} sts assume-role \
-#         --role-arn "arn:aws:iam::${aws_account_id}:role/AWSManagerRole" \
-#         --role-session-name "AwsManagerRoleSession" \
-#         --duration-seconds 900 \
-#       )
-#       AWS_ACCESS_KEY_ID=$(echo ${aws_output} | jq -r '.Credentials.AccessKeyId')
-#       AWS_SECRET_ACCESS_KEY=$(echo ${aws_output} | jq -r '.Credentials.SecretAccessKey')
-#       AWS_SESSION_TOKEN=$(echo ${aws_output} | jq -r '.Credentials.SessionToken')
-#       AWS_SESSION_TOKEN_EXPIRATION=$(echo ${aws_output} | jq -r '.Credentials.Expiration')
-#       echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
-#       echo "AWS_SESSION_TOKEN_EXPIRATION=$AWS_SESSION_TOKEN_EXPIRATION"
-#       if [[ -f ${PRJ_ROOT_DIR}/.env ]]; then
-#         if ! grep -q "AWS_ACCESS_KEY_ID=" ${PRJ_ROOT_DIR}/.env; then
-#           echo "AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'" >> ${PRJ_ROOT_DIR}/.env
-#         else
-#           sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'|" ${PRJ_ROOT_DIR}/.env
-#         fi
-#         if ! grep -q "AWS_SECRET_ACCESS_KEY=" ${PRJ_ROOT_DIR}/.env; then
-#           echo "AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'" >> ${PRJ_ROOT_DIR}/.env
-#         else
-#           sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'|" ${PRJ_ROOT_DIR}/.env
-#         fi
-#         if ! grep -q "AWS_SESSION_TOKEN=" ${PRJ_ROOT_DIR}/.env; then
-#           echo "AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'" >> ${PRJ_ROOT_DIR}/.env
-#         else
-#           sed -i "s|^AWS_SESSION_TOKEN=.*|AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'|" ${PRJ_ROOT_DIR}/.env
-#         fi
-#         if ! grep -q "AWS_SESSION_TOKEN_EXPIRATION=" ${PRJ_ROOT_DIR}/.env; then
-#           echo "AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'" >> ${PRJ_ROOT_DIR}/.env
-#         else
-#           sed -i "s|^AWS_SESSION_TOKEN_EXPIRATION=.*|AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
-#         fi
-#       else
-#         >&2 echo "ERROR: missing ${PRJ_ROOT_DIR}/.env!"
-#       fi
-#     fi
-# }
+  CUR_AWS_ACCESS_KEY_ID=$(cd ${PRJ_ROOT_DIR}; docker ps --filter "name=vice" | grep vice >/dev/null 2>&1 && docker exec -it vice /usr/bin/su --login cyverse -c "bash -i -c 'echo -n \${AWS_ACCESS_KEY_ID}'" | tail -n 1 | tr -d '\n')
+  CUR_AWS_SECRET_ACCESS_KEY=$(cd ${PRJ_ROOT_DIR}; docker ps --filter "name=vice" | grep vice >/dev/null 2>&1 && docker exec -it vice /usr/bin/su --login cyverse -c "bash -i -c 'echo -n \${AWS_SECRET_ACCESS_KEY}'" | tail -n 1 | tr -d '\n')
+  CUR_AWS_SESSION_TOKEN=$(cd ${PRJ_ROOT_DIR}; docker ps --filter "name=vice" | grep vice >/dev/null 2>&1 && docker exec -it vice /usr/bin/su --login cyverse -c "bash -i -c 'echo -n \${AWS_SESSION_TOKEN}'" | tail -n 1 | tr -d '\n')
+  CUR_AWS_CREDENTIAL_EXPIRATION=$(cd ${PRJ_ROOT_DIR}; docker ps --filter "name=vice" | grep vice >/dev/null 2>&1 && docker exec -it vice /usr/bin/su --login cyverse -c "bash -i -c 'echo -n \${AWS_CREDENTIAL_EXPIRATION}'" | tail -n 1 | tr -d '\n')
+  echo "AWS_ACCESS_KEY_ID=$CUR_AWS_ACCESS_KEY_ID"
+  echo "AWS_CREDENTIAL_EXPIRATION=$CUR_AWS_CREDENTIAL_EXPIRATION"
+  if [[ -f ${PRJ_ROOT_DIR}/.env ]]; then
+    if ! grep -q "AWS_ACCESS_KEY_ID=" ${PRJ_ROOT_DIR}/.env; then
+      echo "AWS_ACCESS_KEY_ID='${CUR_AWS_ACCESS_KEY_ID}'" >> ${PRJ_ROOT_DIR}/.env
+    else
+      sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID='${CUR_AWS_ACCESS_KEY_ID}'|" ${PRJ_ROOT_DIR}/.env
+    fi
+
+    if ! grep -q "AWS_SECRET_ACCESS_KEY=" ${PRJ_ROOT_DIR}/.env; then
+      echo "AWS_SECRET_ACCESS_KEY='${CUR_AWS_SECRET_ACCESS_KEY}'" >> ${PRJ_ROOT_DIR}/.env
+    else
+      sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY='${CUR_AWS_SECRET_ACCESS_KEY}'|" ${PRJ_ROOT_DIR}/.env
+    fi
+
+    if ! grep -q "AWS_SESSION_TOKEN=" ${PRJ_ROOT_DIR}/.env; then
+      echo "AWS_SESSION_TOKEN='${CUR_AWS_SESSION_TOKEN}'" >> ${PRJ_ROOT_DIR}/.env
+    else
+      sed -i "s|^AWS_SESSION_TOKEN=.*|AWS_SESSION_TOKEN='${CUR_AWS_SESSION_TOKEN}'|" ${PRJ_ROOT_DIR}/.env
+    fi
+
+    if ! grep -q "AWS_CREDENTIAL_EXPIRATION=" ${PRJ_ROOT_DIR}/.env; then
+      echo "AWS_CREDENTIAL_EXPIRATION='${CUR_AWS_CREDENTIAL_EXPIRATION}'" >> ${PRJ_ROOT_DIR}/.env
+    else
+      sed -i "s|^AWS_CREDENTIAL_EXPIRATION=.*|AWS_CREDENTIAL_EXPIRATION='${CUR_AWS_CREDENTIAL_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
+    fi
+    # Reload the keys
+    source ${PRJ_ROOT_DIR}/.env
+  else
+    >&2 echo "ERROR: missing ${PRJ_ROOT_DIR}/.env!"
+  fi
+}
+
 
 function setup_iam_step_1() {
   STEP_1_FILE="${PRJ_ROOT_DIR}/iam-json-docs/AWSMgrS3Policy.json"
@@ -306,9 +294,9 @@ function setup_iam_step_7() {
     AWS_ACCESS_KEY_ID=$(echo ${aws_output} | jq -r '.Credentials.AccessKeyId')
     AWS_SECRET_ACCESS_KEY=$(echo ${aws_output} | jq -r '.Credentials.SecretAccessKey')
     AWS_SESSION_TOKEN=$(echo ${aws_output} | jq -r '.Credentials.SessionToken')
-    AWS_SESSION_TOKEN_EXPIRATION=$(echo ${aws_output} | jq -r '.Credentials.Expiration')
+    AWS_CREDENTIAL_EXPIRATION=$(echo ${aws_output} | jq -r '.Credentials.Expiration')
     echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
-    echo "AWS_SESSION_TOKEN_EXPIRATION=$AWS_SESSION_TOKEN_EXPIRATION"
+    echo "AWS_CREDENTIAL_EXPIRATION=$AWS_CREDENTIAL_EXPIRATION"
     if [[ -f ${PRJ_ROOT_DIR}/.env ]]; then
       if ! grep -q "AWS_ACCESS_KEY_ID=" ${PRJ_ROOT_DIR}/.env; then
         echo "AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'" >> ${PRJ_ROOT_DIR}/.env
@@ -325,10 +313,10 @@ function setup_iam_step_7() {
       else
         sed -i "s|^AWS_SESSION_TOKEN=.*|AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'|" ${PRJ_ROOT_DIR}/.env
       fi
-      if ! grep -q "AWS_SESSION_TOKEN_EXPIRATION=" ${PRJ_ROOT_DIR}/.env; then
-        echo "AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'" >> ${PRJ_ROOT_DIR}/.env
+      if ! grep -q "AWS_CREDENTIAL_EXPIRATION=" ${PRJ_ROOT_DIR}/.env; then
+        echo "AWS_CREDENTIAL_EXPIRATION='${AWS_CREDENTIAL_EXPIRATION}'" >> ${PRJ_ROOT_DIR}/.env
       else
-        sed -i "s|^AWS_SESSION_TOKEN_EXPIRATION=.*|AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
+        sed -i "s|^AWS_CREDENTIAL_EXPIRATION=.*|AWS_CREDENTIAL_EXPIRATION='${AWS_CREDENTIAL_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
       fi
     else
       >&2 echo "ERROR: missing ${PRJ_ROOT_DIR}/.env!"
@@ -501,8 +489,8 @@ case $command in
     awsmgr=true
     vice=true
     ;;
-  generate-aws-token)
-    generate_aws_token
+  update-key-from-vice)
+    update_keys_from_vice
     exit $?
     ;;
   iam-1)
@@ -529,8 +517,7 @@ case $command in
     setup_iam_step_6 "${_AWSPROFILENAME}"
     exit $?
     ;;
-  generate-aws-token)
-  iam-7)
+  "iam-7"|"generate-aws-token")
     setup_iam_step_7 "${_AWSPROFILENAME}"
     exit $?
     ;;
