tweaks to mk command

diff --git a/bin/mk b/bin/mk
--- a/bin/mk
+++ b/bin/mk
@@ -43,6 +43,7 @@ clean=false
 rebuild_flask=false
 rebuild_node=false
 inject=false
+skip_auth_check='no'
 
 build=true
 shell=false
@@ -73,12 +74,13 @@ function show_help() {
     generate-aws-token  -- Generate temporary token for aws
 
   FLAGS
-    -f/--rebuild-flask  - Builds flask wheel package in dist for awsmgr/vice images
-    -n/--rebuild-node   - Builds NextJS tgz package in dist for awsmgr/vice images
-    -s/--shell          - load shell for pynode/pulumi/awsmgrvice ie 'mk pynode -s'
-    -h/--harbor-tags    - Push to harbor (only works on vice command)
-    -k/--docker-tags    - Push to docker
-    -i/--inject         - Inject updatd project
+    -f/--rebuild-flask   - Builds flask wheel package in dist for awsmgr/vice images
+    -n/--rebuild-node    - Builds NextJS tgz package in dist for awsmgr/vice images
+    -s/--shell           - load shell for pynode/pulumi/awsmgrvice ie 'mk pynode -s'
+    -h/--harbor-tags     - Push to harbor (only works on vice command)
+    -k/--docker-tags     - Push to docker
+    -i/--inject          - Inject updatd project
+    -a/--skip-auth-check - Skip auth check at startup
   """
 }
 
@@ -133,8 +135,15 @@ function get_aws_account_id() {
 }
 
 function generate_aws_token() {
+  if [[ -z ${AWS_ADMIN_PROFILE} ]]; then
+    AWS_ADMIN_PROFILE=default
+    echo "AWS_ADMIN_PROFILE='default'" >> ${PRJ_ROOT_DIR}/.env
+  else
+    echo "Using AWS Profile: $AWS_ADMIN_PROFILE for your cli profile..."
+  fi
+
   aws_account_id=$(\
-      aws --profile ${MK_AWS_PROFILE} \
+      aws --profile ${AWS_ADMIN_PROFILE} \
       sts get-caller-identity \
         | jq -r .Account \
       || { \
@@ -146,21 +155,42 @@ function generate_aws_token() {
     # min 900 seconds or 8 hours max?
     if [[ ! -z ${aws_account_id} ]]; then
       aws_output=$(\
-        aws --profile ${MK_AWS_PROFILE} sts assume-role \
+        aws --profile ${AWS_ADMIN_PROFILE} sts assume-role \
         --role-arn "arn:aws:iam::${aws_account_id}:role/AWSManagerRole" \
         --role-session-name "AwsManagerRoleSession" \
-        --duration-seconds 900\
+        --duration-seconds 900 \
       )
+
+      ## @TODO: fix, needs to attach-role-policy?
       AWS_ACCESS_KEY_ID=$(echo ${aws_output} | jq -r '.Credentials.AccessKeyId')
       AWS_SECRET_ACCESS_KEY=$(echo ${aws_output} | jq -r '.Credentials.SecretAccessKey')
       AWS_SESSION_TOKEN=$(echo ${aws_output} | jq -r '.Credentials.SessionToken')
       AWS_SESSION_TOKEN_EXPIRATION=$(echo ${aws_output} | jq -r '.Credentials.Expiration')
+      echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
       echo "AWS_SESSION_TOKEN_EXPIRATION=$AWS_SESSION_TOKEN_EXPIRATION"
       if [[ -f ${PRJ_ROOT_DIR}/.env ]]; then
-        sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'|" ${PRJ_ROOT_DIR}/.env
-        sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'|" ${PRJ_ROOT_DIR}/.env
-        sed -i "s|^AWS_SESSION_TOKEN=.*|AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'|" ${PRJ_ROOT_DIR}/.env
-        sed -i "s|^AWS_SESSION_TOKEN_EXPIRATION=.*|AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
+        if ! grep -q "AWS_ACCESS_KEY_ID=" ${PRJ_ROOT_DIR}/.env; then
+          echo "AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'" >> ${PRJ_ROOT_DIR}/.env
+        else
+          sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'|" ${PRJ_ROOT_DIR}/.env
+        fi
+        if ! grep -q "AWS_SECRET_ACCESS_KEY=" ${PRJ_ROOT_DIR}/.env; then
+          echo "AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'" >> ${PRJ_ROOT_DIR}/.env
+        else
+          sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'|" ${PRJ_ROOT_DIR}/.env
+        fi
+        if ! grep -q "AWS_SESSION_TOKEN=" ${PRJ_ROOT_DIR}/.env; then
+          echo "AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'" >> ${PRJ_ROOT_DIR}/.env
+        else
+          sed -i "s|^AWS_SESSION_TOKEN=.*|AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'|" ${PRJ_ROOT_DIR}/.env
+        fi
+        if ! grep -q "AWS_SESSION_TOKEN_EXPIRATION=" ${PRJ_ROOT_DIR}/.env; then
+          echo "AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'" >> ${PRJ_ROOT_DIR}/.env
+        else
+          sed -i "s|^AWS_SESSION_TOKEN_EXPIRATION=.*|AWS_SESSION_TOKEN_EXPIRATION='${AWS_SESSION_TOKEN_EXPIRATION}'|" ${PRJ_ROOT_DIR}/.env
+        fi
+      else
+        >&2 echo "ERROR: missing ${PRJ_ROOT_DIR}/.env!"
       fi
     fi
 }
@@ -201,6 +231,9 @@ function parse_long_options() {
       --inject)
         inject=true
         ;;
+      --skip-auth-check)
+        skip_auth_check='yes'
+        ;;
       *)
         # Ignore unknown options
         ;;
@@ -212,7 +245,7 @@ function parse_long_options() {
 parse_long_options "$@"
 
 # Now, handle short options
-while getopts "fnshki" opt; do
+while getopts "fnshkia" opt; do
     case ${opt} in
         f)
             rebuild_flask=true
@@ -240,6 +273,9 @@ while getopts "fnshki" opt; do
           ;;
         i)
           inject=true
+          ;;
+        a)
+          skip_auth_check='yes'
           ;;
         *)
             # Handle error: unknown option
@@ -382,7 +418,7 @@ if [[ ( ( ${awsmgr} == true ) && ( ${build} == true ) ) ]]; then
   time make SKIPFLASKBUILD='yes' SKIPNODEBUILD='yes' LOCALREGISTRY="${local_registry}" DOCKERREGISTRY="${docker_tags}" build-awsmgr-image
   echo "awsmgr build complete"
 elif [[ ( ( ${awsmgr} == true ) && ( ${shell} == true ) ) ]]; then
-  make  shell-awsmgr-image
+  make shell-awsmgr-image
 fi
 
 if [[ ( ( ${vice} == true ) && ( ${build} == true ) ) ]]; then
@@ -392,7 +428,7 @@ if [[ ( ( ${vice} == true ) && ( ${build} == true ) ) ]]; then
   echo "vice build complete"
 elif [[ ( ( ${vice} == true ) && ( ${shell} == true ) ) ]]; then
   echo "Shelling into vice"
-  make shell-vice-image
+  make SKIPAWSAUTH=${skip_auth_check} shell-vice-image
 fi
 
 if [[ $command != 'last' ]]; then
